using Orivy.Controls;
using SkiaSharp;
using System;
using System.Globalization;
using System.Text;

namespace Orivy.Studio;

/// <summary>
/// Generates WinForms-style Designer code (fields + InitializeComponent) from the design surface,
/// ready to paste into an Orivy <c>Window</c> partial class.
/// </summary>
public static class CodeGenerator
{
    public static string Generate(DesignSurface surface, string windowClassName = "MyWindow")
    {
        var root = surface.DesignRoot;
        var sb = new StringBuilder();
        var inv = CultureInfo.InvariantCulture;

        sb.AppendLine("// <auto-generated> Produced by Orivy.Studio — paste into your Window's Designer partial. </auto-generated>");
        sb.AppendLine("using Orivy;");
        sb.AppendLine("using Orivy.Controls;");
        sb.AppendLine("using SkiaSharp;");
        sb.AppendLine();
        sb.AppendLine($"partial class {windowClassName}");
        sb.AppendLine("{");

        var controls = surface.DesignedControls;

        foreach (var control in controls)
            sb.AppendLine($"    private {control.GetType().Name} {control.Name} = null!;");

        sb.AppendLine();
        sb.AppendLine("    private void InitializeComponent()");
        sb.AppendLine("    {");
        sb.AppendLine(string.Format(inv,
            "        ClientSize = new SKSize({0}, {1});",
            (int)root.Width, (int)root.Height));
        sb.AppendLine();

        foreach (var control in controls)
        {
            sb.AppendLine($"        {control.Name} = new {control.GetType().Name}");
            sb.AppendLine("        {");
            sb.AppendLine($"            Name = \"{Escape(control.Name)}\",");
            if (!string.IsNullOrEmpty(control.Text))
                sb.AppendLine($"            Text = \"{Escape(control.Text)}\",");
            sb.AppendLine(string.Format(inv,
                "            Location = new SKPoint({0}, {1}),",
                (int)control.Location.X, (int)control.Location.Y));
            sb.AppendLine(string.Format(inv,
                "            Size = new SKSize({0}, {1}),",
                (int)control.Width, (int)control.Height));
            sb.AppendLine("        };");
        }

        sb.AppendLine();
        foreach (var control in controls)
            sb.AppendLine($"        Controls.Add({control.Name});");

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string Escape(string value) =>
        value.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n").Replace("\r", string.Empty);
}
