using Orivy;
using Orivy.Controls;
using SkiaSharp;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;

namespace Orivy.Studio;

/// <summary>
/// Generates WinForms-style Designer code (fields + InitializeComponent) from the design surface,
/// ready to paste into an Orivy <c>Window</c> partial class. Walks each top-level designed control's
/// own <see cref="ElementBase.Controls"/> recursively, so control groups (see
/// <see cref="DesignSurface.Groups"/>) emit their nested children too, not just the group shell.
/// </summary>
public static class CodeGenerator
{
    public static string Generate(DesignSurface surface, string windowClassName = "MyWindow")
    {
        var root = surface.DesignRoot;
        var sb = new StringBuilder();
        var inv = CultureInfo.InvariantCulture;

        sb.AppendLine("// <auto-generated> Produced by Orivy.Studio — paste into your Window's Designer partial. </auto-generated>");
        sb.AppendLine("using Orivy;");
        sb.AppendLine("using Orivy.Controls;");
        sb.AppendLine("using SkiaSharp;");
        sb.AppendLine();
        sb.AppendLine($"partial class {windowClassName}");
        sb.AppendLine("{");

        var controls = surface.DesignedControls;

        foreach (var control in controls)
            AppendFieldDeclaration(sb, control);

        sb.AppendLine();
        sb.AppendLine("    private void InitializeComponent()");
        sb.AppendLine("    {");
        if (DesignPersistableProperties.ShouldWriteTrackedLayoutProperty(root, "Size"))
        {
            sb.AppendLine(string.Format(inv,
                "        ClientSize = new SKSize({0}, {1});",
                DesignSourceFormat.Pixel(root.Width), DesignSourceFormat.Pixel(root.Height)));
            sb.AppendLine();
        }

        foreach (var control in controls)
            AppendInitializer(sb, control, inv, surface);

        sb.AppendLine();
        foreach (var control in controls)
            AppendAddCalls(sb, control, "Controls");

        sb.AppendLine("    }");
        AppendHandlerMethods(sb, surface);
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void AppendHandlerMethods(StringBuilder sb, DesignSurface surface)
    {
        var seen = new HashSet<string>(StringComparer.Ordinal);
        foreach (var wire in surface.EventWires)
        {
            if (!DesignInteractions.TryPlainHandlerName(wire.Handler, out var name) || !seen.Add(name))
                continue;

            var method = DesignInteractions.FormatHandlerMethod(surface, wire);
            if (method.Length == 0)
                continue;

            sb.AppendLine();
            sb.AppendLine(method);
        }
    }

    private static void AppendFieldDeclaration(StringBuilder sb, ElementBase control)
    {
        sb.AppendLine($"    private {control.GetType().Name} {control.Name} = null!;");
        foreach (var child in NestedDesignedChildren(control))
            AppendFieldDeclaration(sb, child);
    }

    private static void AppendInitializer(StringBuilder sb, ElementBase control, IFormatProvider inv, DesignSurface surface)
    {
        sb.AppendLine($"        {control.Name} = new {control.GetType().Name}");
        sb.AppendLine("        {");
        sb.AppendLine($"            Name = \"{Escape(control.Name)}\",");
        if (DesignPersistableProperties.ShouldWriteTrackedLayoutProperty(control, "Text")
            && !string.IsNullOrEmpty(control.Text))
            sb.AppendLine($"            Text = \"{Escape(control.Text)}\",");
        if (DesignPersistableProperties.ShouldWriteTrackedLayoutProperty(control, "Location"))
        {
            var loc = DesignSourceFormat.PersistedLocation(control);
            sb.AppendLine(string.Format(inv,
                "            Location = new SKPoint({0}, {1}),",
                DesignSourceFormat.Pixel(loc.X), DesignSourceFormat.Pixel(loc.Y)));
        }

        if (DesignPersistableProperties.ShouldWriteTrackedLayoutProperty(control, "Size"))
        {
            sb.AppendLine(string.Format(inv,
                "            Size = new SKSize({0}, {1}),",
                DesignSourceFormat.Pixel(control.Width), DesignSourceFormat.Pixel(control.Height)));
        }

        if (DesignPersistableProperties.ShouldWriteTrackedLayoutProperty(control, "Dock"))
            sb.AppendLine($"            Dock = {DesignSourceFormat.Dock(control.Dock)},");
        if (DesignPersistableProperties.ShouldWriteTrackedLayoutProperty(control, "Anchor"))
            sb.AppendLine($"            Anchor = {DesignSourceFormat.Anchor(control.Anchor)},");
        if (DesignPersistableProperties.ShouldWriteTrackedLayoutProperty(control, "Visible") && !control.Visible)
            sb.AppendLine("            Visible = false,");
        sb.AppendLine("        };");
        AppendControlInteractions(sb, surface, control.Name);

        foreach (var child in NestedDesignedChildren(control))
            AppendInitializer(sb, child, inv, surface);
    }

    private static void AppendControlInteractions(StringBuilder sb, DesignSurface surface, string controlName)
    {
        foreach (var wire in surface.EventWires)
        {
            if (wire.ControlName == controlName && !string.IsNullOrWhiteSpace(wire.Handler))
                sb.AppendLine(DesignInteractions.FormatEvent(wire));
        }

        foreach (var binding in surface.ControlBindings)
        {
            if (binding.ControlName == controlName)
                sb.AppendLine(DesignInteractions.FormatBinding(surface, binding));
        }
    }

    private static void AppendAddCalls(StringBuilder sb, ElementBase control, string parentControlsExpression)
    {
        sb.AppendLine($"        {parentControlsExpression}.Add({control.Name});");

        var childControlsExpression = $"{control.Name}.Controls";
        foreach (var child in NestedDesignedChildren(control))
            AppendAddCalls(sb, child, childControlsExpression);
    }

    /// <summary>A designed control's own children (e.g. a group container's members) — everything
    /// except internal scaffolding like auto-added scroll bars, mirroring the root-level filter in
    /// <see cref="DesignSurface"/>.</summary>
    private static System.Collections.Generic.IEnumerable<ElementBase> NestedDesignedChildren(ElementBase control)
    {
        foreach (var c in control.Controls)
            if (c is ElementBase child and not ScrollBar)
                yield return child;
    }

    private static string Escape(string value) =>
        value.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n").Replace("\r", string.Empty);
}
